name: Sync multiple branches
on:
  push:
    branches:
      - 'release'
jobs:
  sync-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Merge release -> develop
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: release
          target_branch: develop
          github_token: ${{ github.token }}

      - uses: ravsamhq/notify-slack-action@v1
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          token: ${{ github.token }}
          notification_title: 'Syncing from release to develop has {status_message}'
          message_format: '{emoji} *Syncing from release to develop has* {status_message} by ${{ github.event.pusher.name }} at *${{ github.event.head_commit.message }}*'
          footer: 'Resolve conflicts at <{repo_url}/compare/develop...release|{repo}>'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
