name: Sync multiple branches
on:
  push:
    branches:
      - 'main'
jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> release
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: release
          github_token: ${{ github.token }}

      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ github.token }}
          notification_title: 'Syncing from main to release has {status_message}'
          message_format: '{emoji} *{Syncing from main to release has}* {status_message} by ${{ github.event.pusher.name }}'
          footer: 'Resolve conflicts at <{repo_url}/compare/release...main|{repo}>'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: Merge release -> develop
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: release
          target_branch: develop
          github_token: ${{ github.token }}
